runtime: nodejs12

handlers:
  - url: /(.+\.js)
    static_files: dist/\1
    upload: dist/(.+\.js)
    secure: always
    redirect_http_response_code: 301

  - url: /(.+\.css)
    static_files: dist/\1
    upload: dist/(.+\.css)
    secure: always
    redirect_http_response_code: 301

  - url: /(.+\.png)
    static_files: dist/\1
    upload: dist/(.+\.png)
    secure: always
    redirect_http_response_code: 301

  - url: /(.+\.jpg)
    static_files: dist/\1
    upload: dist/(.+\.jpg)
    secure: always
    redirect_http_response_code: 301

  - url: /(.+\.gif)
    static_files: dist/\1
    upload: dist/(.+\.gif)
    secure: always
    redirect_http_response_code: 301

  - url: /(.+\.svg)
    static_files: dist/\1
    upload: dist/(.+\.svg)
    secure: always
    redirect_http_response_code: 301

  - url: /favicon.ico
    static_files: dist/favicon.ico
    upload: dist/favicon.ico
    secure: always
    redirect_http_response_code: 301

  - url: /(.+\.json)
    static_files: dist/\1
    upload: dist/(.+\.json)
    secure: always
    redirect_http_response_code: 301

  - url: /(.+)
    static_files: dist/index.html
    upload: dist/index.html
    secure: always
    redirect_http_response_code: 301

  - url: /
    static_files: dist/index.html
    upload: dist/index.html
    secure: always
    redirect_http_response_code: 301